// FrameJ vers�o 04.18.2
// Gabriel Serr�o, PRECISIONLAB, UFRA, 2018
// Step 2: Com a caca�a selecionada, calcula (sem escala definida) descritores de regi�o, de fronteira e de textura de sua proje��o, descritores de regi�o e de fronteira das proje��es dos ter�os Anterior, M�dio e Posterior como tamb�m as proje��es de m�sculo e gordura expostos utilizando o algoritmo k-means. 
// setTool("rectangle");
// Necessita do GLCM_Texture.class e do ij-plugins_toolkit.jar instalados no ImageJ
run("Set Measurements...", "area mean standard modal min perimeter bounding fit shape feret's integrated median display add redirect=None decimal=3");

selectWindow("RegiaoTotal");
run("Duplicate...", "title=ProjecaoCarcaca.JPG");
run("Colors...", "foreground=black background=green selection=white");
run("Clear Outside");
run("Measure");
saveAs("Results", "C:\\ProjecaoCarcaca.txt");
selectWindow("Results");
close();
run("Duplicate...", "title=GLCMProjecaoCarcaca.JPG");
run("8-bit");
run("GLCM Texture", "enter=1 select=[0 degrees] angular contrast correlation inverse entropy");
saveAs("Results", "C:\\GLCMProjecaoCarcaca.txt");
close();

selectWindow("RegiaoTotal");
run("Duplicate...", "title=[Projecao.JPG]");
run("Colors...", "foreground=black background=green selection=white");
run("Clear Outside");
run("k-means Clustering ...", "number_of_clusters=3 cluster_center_tolerance=0.10000000 enable_randomization_seed randomization_seed=1422 show_clusters_as_centroid_value send_to_results_table");
selectWindow("Cluster centroid values");
run("Duplicate...", "title=[SegmentarProjecaoCarcaca.JPG]");
selectWindow("SegmentarProjecaoCarcaca.JPG");
run("Save", "save=C:\\SegmentarProjecaoCarcaca.tif");
selectWindow("k-means cluster centers");
saveAs("Results", "C:\\RGBClusterCenterProjecaoCarcaca.txt")

selectWindow("Clusters");
run("Close");

selectWindow("Cluster centroid values");
close();

selectWindow("SegmentarProjecaoCarcaca.tif");
run("Select None");
makeRectangle(0, 0, 1154, 944);
run("Duplicate...", "title=[ProjecaoPost.JPG]");

// Color Thresholder 1.51s
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=0;
max[0]=255;
filter[0]="pass";
min[1]=200;
max[1]=255;
filter[1]="pass";
min[2]=136;
max[2]=255;
filter[2]="pass";
for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
// Colour Thresholding-------------
run("Create Selection");
run("Make Inverse");
run("Measure");

saveAs("Results", "C:\\ProjecaoPost.txt");
selectWindow("Results");
selectWindow("ProjecaoPost.JPG");
close();

selectWindow("SegmentarProjecaoCarcaca.tif");
run("Select None");
makeRectangle(0, 944, 1154, 944);
run("Duplicate...", "title=[ProjecaoMedi.JPG]");

// Color Thresholder 1.51s
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=0;
max[0]=255;
filter[0]="pass";
min[1]=200;
max[1]=255;
filter[1]="pass";
min[2]=136;
max[2]=255;
filter[2]="pass";
for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
// Colour Thresholding-------------
run("Create Selection");
run("Make Inverse");
run("Measure");

saveAs("Results", "C:\\ProjecaoMedi.txt");
selectWindow("Results");
selectWindow("ProjecaoMedi.JPG");
close();

selectWindow("SegmentarProjecaoCarcaca.tif");
run("Select None");
makeRectangle(0, 1888, 1154, 944);
run("Duplicate...", "title=[ProjecaoAnte.JPG]");

// Color Thresholder 1.51s
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=0;
max[0]=255;
filter[0]="pass";
min[1]=200;
max[1]=255;
filter[1]="pass";
min[2]=136;
max[2]=255;
filter[2]="pass";
for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
// Colour Thresholding-------------
run("Create Selection");
run("Make Inverse");
run("Measure");

saveAs("Results", "C:\\ProjecaoAnte.txt");

selectWindow("ProjecaoAnte.JPG");
close();

selectWindow("Results");
saveAs("Results", "C:\\ProjecaoTercos.txt")
selectWindow("Results");
run("Close");

selectWindow("SegmentarProjecaoCarcaca.tif");
run("Select None");
run("Duplicate...", "title=[CarneProjecaoCarcaca.JPG]");

// Color Thresholder 1.50i
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=0;
max[0]=255;
filter[0]="pass";
min[1]=75;
max[1]=200;
filter[1]="pass";
min[2]=0;
max[2]=255;
filter[2]="pass";
for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
// Colour Thresholding-------------

run("Save", "save=C:\\CarneProjecaoCarcaca.tif");

selectWindow("CarneProjecaoCarcaca.tif");
setAutoThreshold("Default");
//run("Threshold...");
run("Create Selection");
run("Measure");

selectWindow("SegmentarProjecaoCarcaca.tif");
run("Duplicate...", "title=[GorduraProjecaoCarcaca.JPG]");
// Color Thresholder 1.50i
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=0;
max[0]=255;
filter[0]="pass";
min[1]=0;
max[1]=75;
filter[1]="pass";
min[2]=0;
max[2]=201;
filter[2]="pass";
for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
// Colour Thresholding-------------

run("Save", "save=C:\\GorduraProjecaoCarcaca.tif");

selectWindow("GorduraProjecaoCarcaca.tif");
setAutoThreshold("Default");
//run("Threshold...");
run("Create Selection");
run("Measure");


selectWindow("Results");
saveAs("Results", "C:\\TecidosSegmentadosProjecaoCarcaca.txt")
selectWindow("Results");
run("Close");

selectWindow("CarneProjecaoCarcaca.tif");
run("Duplicate...", "title=[SegmentarCarne.JPG]");
makeRectangle(0, 0, 1154, 944);
run("Duplicate...", "title=CarnePost.JPG");
setAutoThreshold("Default");
//run("Threshold...");
run("Create Selection");
run("Measure");

selectWindow("GorduraProjecaoCarcaca.tif");
run("Duplicate...", "title=[SegmentarGordura.JPG]");
makeRectangle(0, 0, 1154, 944);
run("Duplicate...", "title=GorduraPost.JPG");
setAutoThreshold("Default");
//run("Threshold...");
run("Create Selection");
run("Measure");

selectWindow("CarnePost.JPG");
close();
selectWindow("GorduraPost.JPG");
close();

selectWindow("SegmentarCarne.JPG");
makeRectangle(0, 944, 1154, 944);
run("Duplicate...", "title=CarneMedi.JPG");
setAutoThreshold("Default");
//run("Threshold...");
run("Create Selection");
run("Measure");

selectWindow("SegmentarGordura.JPG");
makeRectangle(0, 944, 1154, 944);
run("Duplicate...", "title=GorduraMedi.JPG");
setAutoThreshold("Default");
//run("Threshold...");
run("Create Selection");
run("Measure");

selectWindow("CarneMedi.JPG");
close();
selectWindow("GorduraMedi.JPG");
close();

selectWindow("SegmentarCarne.JPG");
makeRectangle(0, 1888, 1154, 944);
run("Duplicate...", "title=CarneAnte.JPG");
setAutoThreshold("Default");
//run("Threshold...");
run("Create Selection");
run("Measure");

selectWindow("SegmentarGordura.JPG");
makeRectangle(0, 1888, 1154, 944);
run("Duplicate...", "title=GorduraAnte.JPG");
setAutoThreshold("Default");
//run("Threshold...");
run("Create Selection");
run("Measure");

selectWindow("CarneAnte.JPG");
close();
selectWindow("GorduraAnte.JPG");
close();

selectWindow("SegmentarGordura.JPG");
close();
selectWindow("SegmentarCarne.JPG");
close();

selectWindow("GorduraProjecaoCarcaca.tif");
close();
selectWindow("CarneProjecaoCarcaca.tif");
close();

selectWindow("SegmentarProjecaoCarcaca.tif");
close();
selectWindow("Projecao.JPG");
close();

selectWindow("Results");
saveAs("Results", "C:\\TecidosSegmentadosProjecaoTercos.txt")
selectWindow("Results");
run("Close");

selectWindow("Step 2.ijm");
run("Close")
